#!/bin/bash

BKUPNAME=`date +'zorn-%Y-%m-%d_%H:%M:%S'`
TMPFILE=~/.tarsnap/tmp.log
LOGFILE=~/.tarsnap/tarsnap.log

echo "Backing up to $BKUPNAME" > $TMPFILE
/usr/local/bin/tarsnap -Lcf $BKUPNAME ~/Music ~/Documents ~/Calibre\ Library ~/Pictures ~/bin ~/conf ~/code &>> $TMPFILE
STATUS=$?
echo "Exit $STATUS" >> $TMPFILE

cat $TMPFILE >> $LOGFILE
if [ $STATUS -ne 0 ]; then
    echo "Error in Tarsnap backup!"
    cat $TMPFILE
fi

rm $TMPFILE
exit $STATUS
