# The following lines were added by compinstall
zstyle :compinstall filename '/home/ben/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Set up types to help us be idempotent
# "myconfigs" stores whether each config file did its thing
typeset -A myconfigs
# de-duplicate path entries
typeset -U path
typeset -UT PYTHONPATH pythonpath
typeset -U precmd_functions
typeset -U preexec_functions

# help determine whether commands work
exists () {
    type $* > /dev/null
}
is_osx () {
    [[ `uname` == 'Darwin' ]]
}
is_linux () {
    [[ `uname` == 'Linux' ]]
}

# source ~/conf/setup_paths

ZSH_DIR=~/conf/zsh

source_all_from_dir () {
    for module in $1/*.zsh(N); do
        source $module
    done
}

if is_osx; then
    source_all_from_dir "$ZSH_DIR/osx"
fi
if is_linux; then
    source_all_from_dir "$ZSH_DIR/linux"
fi
source_all_from_dir "$ZSH_DIR"
HOST_CLEANED="$(echo $HOST | sed 's/\..*$//')"
source_all_from_dir "$SZH_DIR/$HOST_CLEANED"

export PYTHONPATH
export PATH
